# Generated by Django 5.1.6 on 2025-03-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroe',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Superheroes.league'),
        ),
        migrations.AlterField(
            model_name='superheroe',
            name='superPowers',
            field=models.ManyToManyField(blank=True, to='Superheroes.superpower'),
        ),
    ]
